<a href="https://colab.research.google.com/github/sazed49/PyTorch_Basics/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi


Mon Nov  3 20:31:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.8.0+cu126
True


##Introduction to Tensors


 ### Creating tensors

In [ ]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])


In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

###random tensors


In [ ]:
 #create a random tensor of size (3,4)
 random_tensor=torch.rand(3,4)
 random_tensor

tensor([[0.2021, 0.8356, 0.4486, 0.7969],
        [0.2300, 0.0615, 0.4231, 0.3296],
        [0.9769, 0.3522, 0.1772, 0.5639]])

In [ ]:
#create a random tensor with similar shape as image

random_image_size_tensor=torch.rand(size=(224,224,3))
#random_image_size_tensor
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### creating range of tensors and tensors-like


In [ ]:
even=torch.arange(0,10,step=1)
even

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating tensors like another one
ten_zeros=torch.zeros_like(input=even)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
float32_tensor=torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False) #whether or not to track gradients with this tensor operations
float32_tensor

tensor([3., 6., 9.])

In [ ]:
torch16_tensor=float32_tensor.type(torch.float16)
torch16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Tensosr Operations

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.31 ms, sys: 0 ns, total: 1.31 ms
Wall time: 1.14 ms


In [ ]:
%%time
tensor.matmul(tensor)


CPU times: user 0 ns, sys: 377 µs, total: 377 µs
Wall time: 326 µs


tensor(14)

###one of the common errors: shape errors




In [ ]:
A=torch.tensor([[1,2],
                [2,3],
                [4,5]])

In [ ]:
B=torch.tensor([[7,10],
                [8,11],
                [9,12]])

In [ ]:
torch.matmul(A,B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# use transpose to solve shape errors
B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(A,B.T)

tensor([[27, 30, 33],
        [44, 49, 54],
        [78, 87, 96]])

### finding min,max,mean, sum etc (tensor aggregation)

In [ ]:
x=torch.arange(1,100,10, dtype=torch.float32)
x

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [ ]:
x.min(), torch.min(x)

(tensor(1.), tensor(1.))

In [ ]:
x.max(), torch.max(x)

(tensor(91.), tensor(91.))

In [ ]:
x.mean(), torch.mean(x)

(tensor(46.), tensor(46.))

In [ ]:
x.sum(), torch.sum(x)

(tensor(460.), tensor(460.))

###finding positional min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors
 * Reshaping- reshapes an input tensor to a defined tensor
 * View- return a view of an input tensor of certain shape but keep the same memory as the original tensor.
 * Stacking- combine multiple tensors on top of each other(vstack) or side by side (hstack)
 * Squeeze- removes all `1` dimensions from a tensor
 * Unsqueeze - add a `1` dimension to a taget tensor.
 * Permute- Return a view of the input with dimensions permuted(swapped) in a certain way.


In [ ]:
x=torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z will change x(as view shares same memory)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
xc_stacked=torch.stack([x,x,x,x],dim=0)
xc_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze()- remove all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeeze=x_reshaped.squeeze()
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:

x_squeeze.shape

torch.Size([9])

In [ ]:
#torch.unsqueeze()- adds a single dimension to a target tensor at a specific dimension
x_unsqueezed=x_squeeze.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
#torch.permute-rearranges the dimensions of a target tensor in a specified order

x_original=torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted=x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x_original[0,0,0]=1234
x_original[0,0,0], x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

## Indexing

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
#x[1][1][1]

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# use ":" to slecet all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th dim and 1st dim but index 1 of 2nd dim
x[::,1]

tensor([[4, 5, 6]])

In [ ]:
# get all from 0th and index 1 of 1st and 2nd
x[:,1,1]

tensor([5])

In [ ]:
#retrun 9
x[0][2][2]
#return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Torch & NumPy
* NumPy to tensor-> `torch.from_numpy(ndarray)`
* t=tensor to NumPy->`torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
 array=array+1
 array,tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
#tensor to numpy
tensor=torch.ones(7)
array=tensor.numpy()
tensor,array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor=tensor+1
tensor,array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reporducibility(trying to take random out of random)
**random seed**-> to reduce randomness
Essentially random seed falvours the randomness


In [ ]:
import torch
tensorA=torch.rand(3,4)
tensorB=torch.rand(3,4)
print(tensorA)
print(tensorB)
print(tensorA==tensorB)

tensor([[0.7048, 0.8377, 0.9514, 0.4566],
        [0.2357, 0.8166, 0.3001, 0.3942],
        [0.1547, 0.6129, 0.1641, 0.4286]])
tensor([[0.9161, 0.9702, 0.4879, 0.0685],
        [0.9514, 0.4515, 0.9538, 0.7114],
        [0.6025, 0.8881, 0.3341, 0.3501]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reporducible tensors
import torch
RANDOM_SEED=42



In [ ]:
torch.manual_seed(RANDOM_SEED)
randomA=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
randomB=torch.rand(3,4)
print(randomA)
print(randomB)
print(randomA==randomB)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (making faster computations)**bold text**

In [ ]:
!nvidia-smi

Mon Nov  3 22:14:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### check for GPU access for PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## putting tensors and models on GPU

In [ ]:
#by default on cpu
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# move tensor to GPU(if avaiable)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### moving tensors back to cpu

In [ ]:
#if tensor is on gpu,can't transfor it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#first set it to cpu
tensor_on_cpu=tensor_on_gpu.cpu()
tensor_on_cpu.numpy()

array([1, 2, 3])